# Schema for the configuration files of the Visual Debugger module.
visual_debugger.settings:
  type: config_object
  label: 'Visual Debugger settings'
  mapping:
    use_on_frontend:
      type: boolean
      label: 'Use Visual Debugger on frontend theme'
    use_on_admin:
      type: boolean
      label: 'Use Visual Debugger on admin theme'
